### PR TITLE
Used Handlebars for templating

### LINKED ISSUE #21: Use HTML template engine
We have repeated snippets of code in our three HTML pages (`index.html`, `sobre.html` and `faq.html`). The DRY philosophy invites use _includes_ to avoid this repetition and enhance maintainability.

### PR DESCRIPTION
**Pull request by siddhant-soni**
fixes #21

### CODE REVIEW

**Comment by gvarandas** [comment]
@siddhant-soni nice job! 🏅 
Just one feedback: some attributes on the head template, like `og:title` and `og:url` are different, based on the page that it was put on.
The template now does not differentiate those, so this should be configurable on the head template.

**Comment by gvarandas** [comment]
One last thing (I guess):
Your Google Tag Manager template `google-analytics.hbs` has some formatting problems, which are causing some errors in the console.
Checked them out here and discovered that they are being caused by the quote marks you used on your code.

Test this block instead of the original and check if it solves the issue:
```html
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-127076320-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag("js", new Date());
  gtag("config", "UA-127076320-1");
</script>
```

You should see no errors in the console whatsoever. 😄

**Comment by siddhant-soni** [comment]
Thank you! It worked. I'll make sure to check the console every time now.

**Comment by cuducos** [comment]
That's great : ) Many thanks @siddhant-soni for the PR and @gvarandas for the code review!

**Pull request merged**
