### PR TITLE
Add gender support to hardcoded strings

### PR DESCRIPTION
**Pull request by guidiego**
I followed some @cuducos instruction on issue #6 and add gender support to a hardcoded part! I inserted the translation inside the same file of the code, maybe we could improve it later :) Let me know if have any other part that I can act before this PR be merged :D

### CODE REVIEW

**Comment by cuducos** [comment]
Hi @guidiego,

Many thanks for this contribution! I think this was a cleaver way to fix #6.

As you've pointed out, I do think we should keep the dictionary of male/female words somewhere else (maybe a new file at `perfil-politico-frontend/src/js/data/`, maybe remember one of the files within this directory to be more generic).

Also I was wondering if we could wait for more contributions in this branch so we have more terms fixed according to the gender. I think there only one or two more occurrences.

What do you all think about that?

**Comment by guidiego** [comment]
@cuducos I totally agree! I think that we could create a new file, yesterday I thought in use one of both already existing, but I reconsidered it, I remembered that we aren't translating anything to put it inside one of them, In my vision will be more clear if we create a file called: `alternative-labels.js` or something like that.

Could you point the other cases? I will jump on it today to help the project!

**Comment by cuducos** [comment]
* Next to the candidate picture there's a _Já foi eleito? _
* In the _Histórico de candidaturas_ chart there's the job title (e.g. _Deputado Federal_ instead of _Deputada Federal_) and, if the person was already elected, _Eleito_ instead of _Eleita_ (including _Nao Eleito_ and _Eleito por QP_, for example)

I think that's all. Have you noticed anything else, @anarute?

**Comment by anarute** [comment]
Nice, great approach!
That's all the places I've noticed too.

**Comment by gvarandas** [comment]
@guidiego there are some conflicts with the `master` branch. Could you investigate, please?

**Comment by guidiego** [comment]
Yeah @gvarandas ley me check it right now!

**Comment by guidiego** [comment]
@cuducos @gvarandas I think that I finished this one :)

**Comment by cuducos** [comment]
Awesome, thank you both <3

**Pull request merged**
