### PR TITLE
issue #20 changing president title

### PR DESCRIPTION
**Pull request by MVictorM**

### CODE REVIEW

**Comment by MVictorM** [comment]
@cuducos sorry, didn't see this change. I'll undo it

**Comment by MVictorM** [comment]
@cuducos done :)

**Comment by cuducos** [comment]
Would you mind rebasing to have only one commit? Probably something like:

```sh
$ git rebase -i HEAD~2
```

Then edit the rebase to:

```
pick 9b13cbe0 issue #20 changing president title
fixup 4da54e4e undoing wrong changes
```

And finally push with `--force` ; )

**Comment by MVictorM** [comment]
> Would you mind rebasing to have only one commit? Probably something like:
> 
> ```shell
> $ git rebase -i HEAD~2
> ```
> 
> Then edit the rebase to:
> 
> ```
> pick 9b13cbe0 issue #20 changing president title
> fixup 4da54e4e undoing wrong changes
> ```
> And finally push with `--force` ; )

Done

**Pull request merged**
